apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: custom
  name: custom-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: custom
  type: LoadBalancer
status:
  loadBalancer: {}
