apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: custom
  name: custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: custom
    spec:
      containers:
      - image: 515921988912.dkr.ecr.ap-south-1.amazonaws.com/my-ecr-repo:5c09a3a65d7b61e25f699857f089134e2f4b6911
        name: my-ecr-repo
        resources: {}
status: {}
