apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: custom
  name: custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: custom
    spec:
      containers:
      - image: {{image}}
        name: my-ecr-repo
        resources: {}
status: {}
